export const FILE = "FILE";
export const GEOMETRY = "GEOMETRY";
export const SLICING = "SLICING";
export const TOTALVERTICES = "TOTALVERTICES";
export const VERTICES = "VERTICES";
export const POLYGON_VERTICES_DEBUG = "POLYGON_VERTICES_DEBUG";
export const POLYGONS_ARRAY_PER_LAYER="POLYGONS_ARRAY_PER_LAYER";
export const ARRAY_OF_POLYGONS_ARRAY_PER_LAYER="ARRAY_OF_POLYGONS_ARRAY_PER_LAYER"